Repository fulopmartin21/HaladoSzoftTech, pull requests merged in 2024-12, with the labels that each got.

#15 Feat: Added comment insertion and select for coffees
  coffeeComments.php
  comment.php
Labels: backend

#16 Add files via upload
  CreateCoffeesTableQuery_2.sql
  CreateDatabaseAndUserTableQuery_2.sql
  CreateOpinionsQuery_2.sql
Labels: backend

#17 PR SchmidtBalint into main
  coffees.php
  details.html
  fetch_search.php
  index.html
  registration.css
  registration.html
  search.html
  style.css
Labels: backend, frontend

#19 Schmidt balint
  details.html
Labels: frontend

#22 Merge SB to main
  index.php
  registration.php
Labels: frontend
