Repository fulopmartin21/HaladoSzoftTech, pull requests merged in 2024-11, with the labels that each got.

#11 Add files via upload
  CreateCoffeesTableQuery.sql
  CreateDatabaseAndUserTableQuery.sql
  CreateOpinionsQuery.sql
Labels: database

#12 Feat: Added registration.php file to the project!
  registration.php
Labels: backend

#13 Feat: Added Coffess.php for coffee selection
  coffees.php
Labels: backend

#14 PR SchmidtBalint to main
  details.html
  details.php
  fetch_coffees.php
  index.html
  style.css
Labels: backend, frontend
